### ISSUE TITLE
[BUG] All controls marked Not_Applicable on results from Inspec 4.18 (waiver_data feild)

### ISSUE THREAD

**Issue by rx294** [mitre/heimdall-lite#183]
**Describe the bug**
When inspec 4.18 results are uploaded HL 2.0 appears to mark all controls as NA.

The issue seems to be incorrect processing of `waiver_data` field.
 
Please note that the presence of ` waiver_data` alone does NOT make it a `Non_Applicable`,  the field has be checked for appropriate contents.
 
If `waiver_data` field is set to an empty `hash` that means waiver has NOT been applied to that control
 

**To Reproduce**
Upload any results from Inspec 4.18

**Expected behavior**
Controls to be bucketed correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/17052944/68826951-31ce6300-066e-11ea-94d1-f5742e5e14d7.png)

**Comment by ejaronne** [comment]
(The code for this may be in inspecjs?)

**Comment by aaronlippold** [comment]
Fixed by #184
