### ISSUE TITLE
include overlay caveat in test and details

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-lite#199]
- [ ] Fix DESC to spell out 'description'
- [ ] Caveat should be above the 'Primary Description' 
- [ ] add others below the primary description
- Suggested Order Text Blocks
- Maintain the 'logic' on `Justification` title replacement for Not Applicable conditions - this should move to the Slot logic?

see: https://www.vuemastery.com/courses/component-design-patterns/slots-fundamentals 

  1. Caveat
  2. Primary Description
  3. Other subs
  4. Check and Fix

So the Slot order should be in both the Results and the Details Tab.
- `caveat`
- `description main`
- `other sub-descriptions.each`

If a caveat is placed in an overlay, such as to make something N/A with an impact of zero:
![image](https://user-images.githubusercontent.com/34140975/72919284-315ce300-3d15-11ea-9891-fbc4a8a981c8.png)

Then place caveat text here, adding a header for the sub-description as we do for 'Justification:'
![image](https://user-images.githubusercontent.com/34140975/72919893-40906080-3d16-11ea-929a-132e881a700f.png)

and here, also add a header for each sub-description so that it all flows: e.g. 'Caveat:': \n "text" etc.
![image](https://user-images.githubusercontent.com/34140975/72920118-a8df4200-3d16-11ea-8f20-7492c32650c8.png)

**Comment by aaronlippold** [comment]
Should this be rolled into our current EPICs?

**Comment by aaronlippold** [comment]
@Mitriol would this require updates to inspecjs?

**Comment by aaronlippold** [comment]
@cjdoherty this would be a great use of <slots> in the component

**Comment by aaronlippold** [comment]
Slots in the components
