### ISSUE TITLE
Expand CAAT to cover report for all NIST tag entries

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall-lite#214]
Currently the CAAT file exporter chooses only the first NIST entry in the tag 'nist' array.
Proposing expanding the export to report a row for each entry (padded and rounded up to the control or control enhancement level). 

So, for https://github.com/mitre/canonical-ubuntu-16.04-lts-stig-baseline/blob/master/controls/V-75789.rb, the nist array is:

tag "nist": ['AU-3', 'AU-3 (1)', 'AU-12 a', 'AU-12 c', 'MA-4 (1) (a)', 'Rev_4']

but the current export is only ONE row for AU-03.

proposed is to export, in this case, FOUR rows, for AU-03, AU-03(01), AU-12, and MA-04(01). (Same content for elements to the right of the control column.)

Before:
Control Number | Finding Title | Date Identified | Finding ID
-- | -- | -- | --
AU-03 | Test V-75789 - Successful/unsuccessful uses of the pam_timestamp_check   command must generate an audit record. | 08/06/2019 |  

After:
Control Number | Finding Title | Date Identified | Finding ID
-- | -- | -- | --
AU-03 | Test V-75789 - Successful/unsuccessful uses of the pam_timestamp_check   command must generate an audit record. | 08/06/2019 |  
AU-03(01) | Test V-75789 - Successful/unsuccessful uses of the pam_timestamp_check   command must generate an audit record. | 08/06/2019 |  
AU-12 | Test V-75789 - Successful/unsuccessful uses of the pam_timestamp_check   command must generate an audit record. | 08/06/2019 |  
MA-04(01) | Test V-75789 - Successful/unsuccessful uses of the pam_timestamp_check   command must generate an audit record. | 08/06/2019 |

**Comment by Mitriol** [comment]
I will look into this. While I am though, are you sue you want AU-03 and AU-03(01) to both be represented?

**Comment by ejaronne** [comment]
As the example shows, yes both AU-03 and AU-03(01). 

In NIST SP 800-53 parlance, there are security controls, like AU-03, and security control enhancements AU-03(01).  We stop at this level of granularity for the CAAT reporting.

FYI: 
'AU-12 a' and 'AU-12 c' are not "security controls", rather, they are **_pieces_** of the security control called AU-12.
Likewise, 'MA-4 (1) (a)' is only **_part_** of a security control enhancement.
So, these are "too" detailed, so to speak for the CAAT. 
We don't abandon them though! Rather, we "round up" to the nearest security control or security control enhancement.

That is why, even though there are five "things" mentioned in the nist array:
'AU-3', 'AU-3 (1)', **_'AU-12 a', 'AU-12 c'_**, 'MA-4 (1) (a)'

we only want four rows for:
AU-03, AU-03(01), AU-12, and MA-04(01)

We do not want to repeat AU-12 twice. Serves no purpose for the CAAT granularity.
