### ISSUE TITLE
Does not deconflict the same file uploaded mulitiple times

### ISSUE THREAD

**Issue by Bialogs** [mitre/heimdall-lite#264]
I can upload the same `OWASP ZAP Zero_WebAppSecurity Heimdall_tools Sample` then view all reports and it just adds up everything treating it as separate even though they have the same SHA256 hash.

I guess what is the hash for?

Would be nice for the app to deconflict stuff like this and check if the hash is already present.

**Comment by robthew** [comment]
The hash is only a hash of the profile. It is not a hash of any of the test results data. The hash should allow us to group all the uploads from the same profile and compare the results
